In [3]:
#Variavel inteira
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [4]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)

1.0


float

In [5]:
# Converter float para int
c = int(b)
print(c)
type(c)

1


int

In [6]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [7]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


In [8]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


In [9]:
a == 1

True

In [10]:
h = (a==1)
print(h)
type(h)

True


bool

In [13]:
i = True
type(i)

bool

In [14]:
ii = 'true'
type (ii)

str

In [15]:
# Operação ==
a==b

True

In [16]:
 # Operação ><
a>b

False

In [17]:
# Operação !=
a!=b

False

In [18]:
# Operação >= ou <=
a>=b

True

In [19]:
# Soma 
a+b

2.0

In [20]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [21]:
# Divisão
a/b

1.0

In [22]:
# Potencia
5**2

25

In [23]:
#Operações matemáticas com a biblioteca math
import math

math.exp(10)

22026.465794806718

In [24]:
math.exp(0)

1.0

In [25]:
math.exp(a)

2.718281828459045

In [26]:
math.exp(-10)

4.5399929762484854e-05

In [27]:
import math as mt
mt.log(c)

0.0

In [28]:
mt.log10(100)

2.0

In [31]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [32]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])

1
3


In [33]:
myFirstList==a

False

In [34]:
myFirstList[0]==a

True

In [35]:
mySeclist = [1,a,'c']
print(mySeclist)


[1, 1, 'c']


In [36]:
type(mySeclist)

list

In [37]:
type(mySeclist[2])

str

In [38]:
type(mySeclist[1])

int

In [42]:
path =  r"C:\Users\marcos perrude\Downloads\poluicao\ENS5173_202401"
print(path)

C:\Users\marcos perrude\Downloads\poluicao\ENS5173_202401


In [43]:
import os
# Listar arquivos na pasta
os.listdir(path)

['.git', '.gitignore', 'Aula1.ipynb', 'inputs', 'README.md', 'scripts', 'venv']

In [44]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [45]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:\\Users\\marcos perrude\\Downloads\\poluicao\\ENS5173_202401/.git'

In [46]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [47]:
# Diretório que estou trababalhando
os.getcwd()

'C:\\Users\\marcos perrude\\Downloads\\poluicao\\ENS5173_202401\\venv'

In [48]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\marcos perrude\Downloads\poluicao\ENS5173_202401\venv/test


In [49]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\marcos perrude\Downloads\poluicao\ENS5173_202401\venv/test2


In [50]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [51]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [52]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[0.96176441 0.36583817 0.51604599 0.09006722 0.81786202 0.53978924
  0.85042899 0.55810944 0.19247733 0.15301085]
 [0.55961322 0.04910317 0.51235566 0.69856061 0.79719248 0.2097622
  0.52307724 0.49104509 0.86786475 0.44537161]
 [0.20162502 0.89342647 0.49059658 0.62039629 0.51699208 0.22240954
  0.45855876 0.84597048 0.8789759  0.04337537]
 [0.46248363 0.69975453 0.21366038 0.33264311 0.40764401 0.80798061
  0.43993823 0.36391786 0.78708654 0.81667513]
 [0.90936779 0.56225694 0.0102411  0.31977055 0.9356896  0.60531717
  0.10105409 0.3340171  0.97075637 0.5391646 ]
 [0.9946603  0.73413234 0.18438572 0.88170662 0.08218352 0.97094343
  0.89441804 0.0369579  0.35088396 0.40653199]
 [0.60415987 0.66261908 0.97218568 0.66319143 0.82689076 0.76015456
  0.60245002 0.07397205 0.87041514 0.47402771]
 [0.28474452 0.5183551  0.85861561 0.16410555 0.16135575 0.27624295
  0.76254957 0.2285749  0.77155379 0.18149067]
 [0.42901203 0.55033696 0.22950066 0.23523643 0.49611693 0.63288703
  0.26411499 

In [53]:
# Acessando valores da matriz
n[0,:]

array([0.96176441, 0.36583817, 0.51604599, 0.09006722, 0.81786202,
       0.53978924, 0.85042899, 0.55810944, 0.19247733, 0.15301085])

In [54]:
n[:,1:5]

array([[0.36583817, 0.51604599, 0.09006722, 0.81786202],
       [0.04910317, 0.51235566, 0.69856061, 0.79719248],
       [0.89342647, 0.49059658, 0.62039629, 0.51699208],
       [0.69975453, 0.21366038, 0.33264311, 0.40764401],
       [0.56225694, 0.0102411 , 0.31977055, 0.9356896 ],
       [0.73413234, 0.18438572, 0.88170662, 0.08218352],
       [0.66261908, 0.97218568, 0.66319143, 0.82689076],
       [0.5183551 , 0.85861561, 0.16410555, 0.16135575],
       [0.55033696, 0.22950066, 0.23523643, 0.49611693],
       [0.42927842, 0.65693279, 0.44024208, 0.26722171]])

In [55]:
n[0,1:5]

array([0.36583817, 0.51604599, 0.09006722, 0.81786202])

In [56]:
n[0,-1]

0.15301085446607354

In [57]:
n[0,4:-1]

array([0.81786202, 0.53978924, 0.85042899, 0.55810944, 0.19247733])

In [58]:
n[0,4:]

array([0.81786202, 0.53978924, 0.85042899, 0.55810944, 0.19247733,
       0.15301085])

In [59]:
an = np.log(n*5)
print(an)

[[ 1.57045216  0.60387372  0.94787853 -0.79776106  1.40837627  0.99286141
   1.44742354  1.02623771 -0.03833899 -0.2678085 ]
 [ 1.0289285  -1.40439382  0.94070167  1.25070459  1.38277879  0.04765716
   0.96141178  0.89821859  1.46771852  0.80059165]
 [ 0.00809229  1.49674667  0.89730479  1.13204108  0.94971019  0.1062031
   0.82977108  1.4421671   1.48044011 -1.52842564]
 [ 0.8382938   1.25241223  0.06607036  0.50875282  0.7120769   1.3962207
   0.78831696  0.59861082  1.37002084  1.40692402]
 [ 1.51443225  1.03364156 -2.97190871  0.46928634  1.54296643  1.10743521
  -0.68266146  0.51287481  1.57975816  0.99170354]
 [ 1.60408391  1.30037194 -0.08128748  1.483542   -0.88936256  1.57995084
   1.49785591 -1.68853783  0.5621382   0.70934526]
 [ 1.10552149  1.19788292  1.58122944  1.19874632  1.41935523  1.33520442
   1.10268733 -0.99463009  1.4706529   0.86294841]
 [ 0.353275    0.95234316  1.45700397 -0.19780755 -0.2147058   0.32296338
   1.33835016  0.13354659  1.35008903 -0.09711314]
 [